name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run ruff linter
        run: |
          ruff check .

      - name: Run mypy type checker
        run: |
          mypy exercises/ solutions/ scripts/ || true

      - name: Run tests
        run: |
          pytest -v tests/
        env:
          # Tests use mocks, so no real API key needed
          OPENAI_API_KEY: "sk-test-key-for-ci"
